### ISSUE TITLE
[Bug] Signing up with an account that already exists doesn’t show the error in the UI.

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/website#149]
### Description of the Bug

Signing up with an account that already exists doesn’t show the error in the UI.

### Reproduction Steps

- Create an account.
- Sign out.
- Try to create and account with the same email address.

### Expected Behaviour

Should show an error message in the sign up bx like "Account already exists, please sign in instead."

### OS

macOS

**Comment by phoenixpereira** [comment]
@Techngo10 will be working on this.

**Comment by devansh-m12** [comment]
can i work on it ?

**Comment by Techngo10** [comment]
Uploaded Fix into <email> branch, I don't know how to check if it works tho
