### ISSUE TITLE
[Bug] Github Actions can't use secrets for forked repos

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/website#155]
### Description of the Bug

Github Actions can't use secrets for forked repos.

### Reproduction Steps

1. Fork a repo and make a PR.
2. Run GitHub Actions and it fails to build the dockerfile due to missing environment secrets.

### Expected Behaviour

It shouldn't fail building the dockerfile.

### OS

macOS

### Additional Notes

Would probably have to hardcode the placeholder environment variables in `ci-dev-pr.yml` to fix this issue.

**Comment by rayokamoto** [comment]
I'm not a huge fan of hard coding environment variables. Are there other methods of enabling the use of environment variables and secrets for PRs made from forked repos?
