### ISSUE TITLE
[Feature Request] Add a more obvious button to the open source page

### ISSUE THREAD

**Issue by jsun969** [compsci-adl/website#163]
### Overview

Add more obvious button for new members signing up open source team volunteer.

### Details

Add a "Join Us Now" button between "who is" and projects in open source page. It will link to the open source sign-up form.

### Why would this feature be useful?

Better for new ppl to sign up

**Comment by KnightRadiant44** [comment]
I'll take a look at this after uni. Feel free to assign this to me.

**Comment by yiukuenchu** [comment]
Ohh, I saw this is already assigned to @KnightRadiant44 after I raised a PR [here](https://github.com/compsci-adl/website/pull/164)

**Comment by jsun969** [comment]
dw, I can assign this to you @yiukuenchu

**Comment by phoenixpereira** [comment]
Fixed in #164
