### ISSUE TITLE
[Feature Request] Improve Open Source Page Design

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/website#165]
### Overview

Improve the design of the open source page to make it look more appealing.

### Details

Make it look like attached screenshot.

### Why would this feature be useful?

Adding the open source drawing and improving the layout would increase the visual appeal.

### Additional Notes

Mockup:

<img src="https://github.com/user-attachments/assets/da16569b-b003-4216-bf92-90211cc6bfe1" width="600"/>

The image to use:

<img src="https://github.com/user-attachments/assets/da802346-7089-4956-81f3-adad17f8dadc" width="400"/>

**Comment by rayokamoto** [comment]
From https://github.com/compsci-adl/website/pull/164#issuecomment-2265714152

> In regards to that design mock up, the "Who is the open source team" part should be much larger as that's important in establishing who the team is, and the team's goals.

**Comment by codingzilin** [comment]
Hi Phoenix, I'd like to take this

**Comment by phoenixpereira** [comment]
@codingzilin I've assigned you to this issue. Also, I have updated the mockup and attached the image that you'll need.

**Comment by codingzilin** [comment]
> @codingzilin I've assigned you to this issue. Also, I have updated the mockup and attached the image that you'll need.

Hi Phoenix, could you pls check the image access? I can't download it, thx
