### ISSUE TITLE
[Feature Request] Upcoming Events on Home Page

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/website#166]
### Overview

Add up to three upcoming events on home page.

### Details

See attached screenshot.

If there and no events, hide this component completely. 

### Why would this feature be useful?

So that people can more easily see upcoming CS Club events.

### Additional Notes

<img width="795" alt="image" src="https://github.com/user-attachments/assets/11d74fa8-276d-4dc3-ba39-18b7ed89fa7b">

**Comment by codingzilin** [comment]
Hi Phoenix, I'd like to do this issue
