### ISSUE TITLE
[Bug] Fix time being UTC instead of ACST

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/website#177]
### Description of the Bug

Event's don't end at the correct time due to the code basing the end time on UTC instead of ACST.

### Reproduction Steps

1. Go to the website after an event has ended (up to a few hours ago)
2. Notice that the event still shows up as upcoming rather than past.

### Expected Behaviour

The events should end at the correct time and use ACST.

### OS

macOS

### Additional Notes

Server time must remain using UTC, so a code change is needed to fix this. Perhaps have a function to convert the `endDate` for each event from ACST to UTC.

**Comment by shfc** [comment]
Hi @phoenixpereira, I want to try to fix this issue.
