### ISSUE TITLE
Reuse top padding & page size in layout

### ISSUE THREAD

**Issue by jsun969** [compsci-adl/website#32]
https://github.com/compsci-adl/website/blob/b14e8d3296809da7153d09e5c7d2f9a388b5a8d6/src/app/contact/page.tsx#L8

Reuse it in `layout.tsx`

**Comment by rayokamoto** [comment]
Do you mean the `layout.tsx` for all pages or just for the contact page?

**Comment by jsun969** [comment]
I mean in `layout.tsx` for all pages. Then we don't need to write the same style in each page.

**Comment by rayokamoto** [comment]
Right, yeah. If it's being reused in all of the pages then adding it to the base `layout.tsx` file wouldn't hurt.
