### ISSUE TITLE
[Feature Request] Middleware for account system

### ISSUE THREAD

**Issue by jsun969** [compsci-adl/website#36]
### Overview

Middleware should be modified according our account system logic. Especially **login**.

### Remove the unnecessary `publicRoutes`

https://github.com/compsci-adl/website/blob/7f2b0e20fabc90be5252a000f1214f0f4315497d/src/middleware.ts#L3-L15

There is no need to add all public routes. Just focus on the routes need auth.

### Add new logic

- Sign in
	- Member -> `user setting / home page`
	- Not Member -> `/join-us`
- Sign up -> No new logic is needed in middleware.

### Why would this feature be useful?

Better UX for login

### Additional Notes

Docs: https://clerk.com/docs/references/nextjs/auth-middleware#use-after-auth-for-fine-grained-control

**Comment by rayokamoto** [comment]
> There is no need to add all public routes. Just focus on the routes need auth.

I agree, that would be a much simpler way of doing things.

**Comment by jsun969** [comment]
There should be a renewal page for whose membership expired

**Comment by rayokamoto** [comment]
I also want to suggest that we rename `/join-us` to simply `/join` as that's shorter and easier to type out. I also suggest that we rename `/sign-in` to `/signin` or `/login`
