### ISSUE TITLE
[Bug] Mobile menu remains open on window resize

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/website#42]
### Description of the Bug

On desktop, the mobile menu remains open if even the widow width has increased.

### Reproduction Steps

1. Open the home page and make the windows size small to match mobile.
2. Click on the mobile menu button
3. Resize window to be bigger/fullscreen and notice that the mobile menu doesn't automatically close.

### Expected Behaviour

The mobile menu should automatically close when the window width increases.

### OS

macOS

### Browser

Safari

**Comment by rayokamoto** [comment]
Resolved by #48
