### ISSUE TITLE
Adjust membership expiry date to end of year

### ISSUE THREAD

**Issue by phoenixpereira** [compsci-adl/website#54]
Adjust membership expiry date to end of year instead of 1 year from sign up for ease of renewals.

**Comment by rayokamoto** [comment]
If it hasn't been done already, we should add a clarifying note that all memberships expire at the end of the year

**Comment by rayokamoto** [comment]
#49 now ensures that the expiry date is the start of the following year. We now need to ensure that the clarifying note is in there.

**Comment by jsun969** [comment]
can this be closed?

**Comment by phoenixpereira** [comment]
The join us page currently says the membership lasts for the full year which should be sufficient, but it might be better to say that the membership ends on the 1/1 of the following year.

**Comment by rayokamoto** [comment]
The site now has the date formatted as `01/01/YYYY` (as of #81). Closing this issue.
